### ISSUE TITLE
Problema cache (?) Firefox

### ISSUE THREAD

**Issue by gherozz** [gherozz/RandomDungeon#6]
Firefox di merda, al reload della pagina mantiene in memoria alcuni elementi della sessione precedente:
- il nome dell'eroe rimane dalla sessione precedente, non modificabile (si rende non modificabile al primo clic del bottone-gioco)
- se il reload avviene **durante** il log di un combattimento il bottone-gioco rimane non cliccabile (ricorda la "non cliccabilità" della sessione precedente)

**Comment by Uomoz** [comment]
dopo la partita do un occhiata!

**Comment by gherozz** [comment]
il bottone adesso non so perché ma sembra essere risolto, rimane il problema del nome dell'eroe

**Comment by Uomoz** [comment]
il nome dell'eroe é una bella menata, con ctrl-f5 pulisce la cache e funziona. Guarderó altre soluzioni online

**Comment by Uomoz** [comment]
For a input tag there's the attribute autocomplete you can set:

<input type="text" autocomplete="off" />
You can use autocomplete for a form too.

**Comment by Uomoz** [comment]
<input type="text" autocomplete="off" />

**Comment by Uomoz** [comment]
For a input tag there's the attribute autocomplete you can set:
<input type="text" autocomplete="off" />
You can use autocomplete for a form too.

**Comment by Uomoz** [comment]
For a input tag there's the attribute autocomplete you can set:
//<input type="text" autocomplete="off" />
You can use autocomplete for a form too.

**Comment by Uomoz** [comment]
For a input tag there's the attribute autocomplete you can set:
`<input type="text" autocomplete="off" />`
You can use autocomplete for a form too.

**Comment by Uomoz** [comment]
funziona, committo
